### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Z-fly** [fjcanyue/comic_downloader#12]
![image](https://github.com/fjcanyue/comic_downloader/assets/10470892/f6673a67-520b-47e7-9912-73768002d9b0)

**Comment by Z-fly** [comment]
动漫之家无法爬
![image](https://github.com/fjcanyue/comic_downloader/assets/10470892/3886e73b-4638-4166-b7a3-d9094683a0a4)

**Comment by fjcanyue** [comment]
不再支持从动漫之家下载了
